/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import modelo.Listado;
import static vista.FrmMenu.jDesktopPane_menu;


/**
 * Esta clase representa la ventana principal del sistema, que proporciona
 * acceso a diferentes funcionalidades.
 *
 * @author Miguel
 * @since 2024-06-07
 */
public class FrmMenuPlebs extends javax.swing.JFrame {
    
    /**
     * Panel de escritorio para gestionar las ventanas internas.
     */
    public static JDesktopPane jDesktopPane_menu;
    
    /**
     * Crea una nueva instancia de FrmMenu.
     */
    public FrmMenuPlebs() {
        initComponents();
        this.setSize(new Dimension(800,700));
        this.setLocationRelativeTo(null);
        this.setTitle("Carnicería");
        
        
        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();
        jDesktopPane_menu.setBackground(Color.pink);

        
        int width = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int height = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, width, (height-110));
        this.add(jDesktopPane_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_clienta = new javax.swing.JMenuItem();
        jMenuItem_clientm = new javax.swing.JMenuItem();
        jMenuItem_clientl = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_producta = new javax.swing.JMenuItem();
        jMenuItem_productm = new javax.swing.JMenuItem();
        jMenuItem_productl = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_ordera = new javax.swing.JMenuItem();
        jMenuItem_orderl = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 153));

        jMenu2.setBackground(new java.awt.Color(255, 153, 153));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-presupuesto-50.png"))); // NOI18N
        jMenu2.setText("Clients");
        jMenu2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jMenu2.setMinimumSize(new java.awt.Dimension(200, 500));
        jMenu2.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem_clienta.setBackground(new java.awt.Color(255, 153, 153));
        jMenuItem_clienta.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jMenuItem_clienta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-más-50.png"))); // NOI18N
        jMenuItem_clienta.setText("New Client");
        jMenuItem_clienta.setPreferredSize(new java.awt.Dimension(200, 50));
        jMenuItem_clienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_clientaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_clienta);

        jMenuItem_clientm.setBackground(new java.awt.Color(255, 153, 153));
        jMenuItem_clientm.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jMenuItem_clientm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ajustes-50.png"))); // NOI18N
        jMenuItem_clientm.setText("Client Management");
        jMenuItem_clientm.setPreferredSize(new java.awt.Dimension(200, 50));
        jMenuItem_clientm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_clientmActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_clientm);

        jMenuItem_clientl.setBackground(new java.awt.Color(255, 153, 153));
        jMenuItem_clientl.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jMenuItem_clientl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-orden-de-compra-50.png"))); // NOI18N
        jMenuItem_clientl.setText("Client List");
        jMenuItem_clientl.setPreferredSize(new java.awt.Dimension(200, 50));
        jMenuItem_clientl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_clientlActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_clientl);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 153, 153));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-bistec-poco-hecho-50.png"))); // NOI18N
        jMenu3.setText("Products");
        jMenu3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jMenu3.setMinimumSize(new java.awt.Dimension(200, 500));
        jMenu3.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem_producta.setBackground(new java.awt.Color(255, 153, 153));
        jMenuItem_producta.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jMenuItem_producta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-más-50.png"))); // NOI18N
        jMenuItem_producta.setText("New Product");
        jMenuItem_producta.setPreferredSize(new java.awt.Dimension(200, 50));
        jMenuItem_producta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_productaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_producta);

        jMenuItem_productm.setBackground(new java.awt.Color(255, 153, 153));
        jMenuItem_productm.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jMenuItem_productm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ajustes-50.png"))); // NOI18N
        jMenuItem_productm.setText("Product Management");
        jMenuItem_productm.setPreferredSize(new java.awt.Dimension(200, 50));
        jMenuItem_productm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_productmActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_productm);

        jMenuItem_productl.setBackground(new java.awt.Color(255, 153, 153));
        jMenuItem_productl.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jMenuItem_productl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-orden-de-compra-50.png"))); // NOI18N
        jMenuItem_productl.setText("Products List");
        jMenuItem_productl.setPreferredSize(new java.awt.Dimension(200, 50));
        jMenuItem_productl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_productlActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_productl);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 153, 153));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-orden-de-compra-50.png"))); // NOI18N
        jMenu4.setText("Orders");
        jMenu4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jMenu4.setMinimumSize(new java.awt.Dimension(200, 500));
        jMenu4.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem_ordera.setBackground(new java.awt.Color(255, 153, 153));
        jMenuItem_ordera.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jMenuItem_ordera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-más-50.png"))); // NOI18N
        jMenuItem_ordera.setText("New Order");
        jMenuItem_ordera.setPreferredSize(new java.awt.Dimension(200, 50));
        jMenuItem_ordera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_orderaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_ordera);

        jMenuItem_orderl.setBackground(new java.awt.Color(255, 153, 153));
        jMenuItem_orderl.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jMenuItem_orderl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-orden-de-compra-50.png"))); // NOI18N
        jMenuItem_orderl.setText("Orders List");
        jMenuItem_orderl.setPreferredSize(new java.awt.Dimension(200, 50));
        jMenuItem_orderl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_orderlActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_orderl);

        jMenuBar1.add(jMenu4);

        jMenu6.setBackground(new java.awt.Color(255, 153, 153));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ventana-abierta-50.png"))); // NOI18N
        jMenu6.setText("Log Out");
        jMenu6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jMenu6.setMinimumSize(new java.awt.Dimension(200, 500));
        jMenu6.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem_logout.setBackground(new java.awt.Color(255, 153, 153));
        jMenuItem_logout.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jMenuItem_logout.setText("Log Out");
        jMenuItem_logout.setPreferredSize(new java.awt.Dimension(185, 50));
        jMenuItem_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_logoutActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_logout);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_clientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_clientaActionPerformed
        InterCliente intercliente = new InterCliente();
        jDesktopPane_menu.add(intercliente);
        intercliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_clientaActionPerformed

    private void jMenuItem_clientmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_clientmActionPerformed
        InterGestCliente intergestcliente = new InterGestCliente();
        jDesktopPane_menu.add(intergestcliente);
        intergestcliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_clientmActionPerformed

    private void jMenuItem_clientlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_clientlActionPerformed
        Listado listado = new Listado();
        listado.listaClientes();
    }//GEN-LAST:event_jMenuItem_clientlActionPerformed

    private void jMenuItem_productaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_productaActionPerformed
        InterProducto interproducto = new InterProducto();
        jDesktopPane_menu.add(interproducto);
        interproducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem_productaActionPerformed

    private void jMenuItem_productmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_productmActionPerformed
        InterGestProducto interGestProducto = new InterGestProducto();
        jDesktopPane_menu.add(interGestProducto);
        interGestProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem_productmActionPerformed

    private void jMenuItem_productlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_productlActionPerformed
        Listado listado = new Listado();
        listado.listaProductos();
    }//GEN-LAST:event_jMenuItem_productlActionPerformed

    private void jMenuItem_orderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_orderaActionPerformed
        InterFactura interFactura = new InterFactura();
        jDesktopPane_menu.add(interFactura);
        interFactura.setVisible(true);
    }//GEN-LAST:event_jMenuItem_orderaActionPerformed

    private void jMenuItem_orderlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_orderlActionPerformed
        Listado listado = new Listado();
        listado.listaVentas();
    }//GEN-LAST:event_jMenuItem_orderlActionPerformed

    private void jMenuItem_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_logoutActionPerformed
        FrmLogin frmlogin = new FrmLogin();
        frmlogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPlebs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPlebs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPlebs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPlebs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPlebs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_clienta;
    private javax.swing.JMenuItem jMenuItem_clientl;
    private javax.swing.JMenuItem jMenuItem_clientm;
    private javax.swing.JMenuItem jMenuItem_logout;
    private javax.swing.JMenuItem jMenuItem_ordera;
    private javax.swing.JMenuItem jMenuItem_orderl;
    private javax.swing.JMenuItem jMenuItem_producta;
    private javax.swing.JMenuItem jMenuItem_productl;
    private javax.swing.JMenuItem jMenuItem_productm;
    // End of variables declaration//GEN-END:variables
}
